services:
  api:
    image: ruby:latest
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      FRONTEND_URL: http://localhost:5173
    entrypoint: ./entrypoint.sh

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: task_list_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  rubygems:
  database: